"""add image_url to chat_history

Revision ID: a9628b133002
Revises: 687d0bab4b53
Create Date: 2025-04-24 17:43:16.937428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9628b133002'
down_revision: Union[str, None] = '687d0bab4b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_index('ix_users_password', table_name='users')
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.create_index('ix_users_password', 'users', ['password'], unique=True)
    op.drop_column('chat_history', 'image_url')
    # ### end Alembic commands ###
